### ISSUE TITLE
Recursion Error

### ISSUE THREAD

**Issue by kj-lai** [magic282/SEASS#6]
Hi @magic282,

I encountered a problem when running `run.sh`, hope you can give me some advice on this problem. Thank you.

```
2018-11-21 14:25:48,687 [INFO:onlinePreprocess]: Prepared 3803957 sentences (0 ignored due to length == 0 or > 100)
2018-11-21 14:25:48,692 [INFO:__main__]:  * vocabulary size. source = 119503; target = 68885
2018-11-21 14:25:48,693 [INFO:__main__]:  * number of training sentences. 3803957
2018-11-21 14:25:48,693 [INFO:__main__]:  * maximum batch size. 64
2018-11-21 14:25:48,693 [INFO:__main__]: Building model...
/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
2018-11-21 14:25:49,457 [INFO:__main__]: encoder.word_lut.weight
Traceback (most recent call last):
  File "train.py", line 331, in <module>
    main()
  File "train.py", line 307, in main
    xavier_normal(p, math.sqrt(3))
  File "/seass/code/SEASS/seq2seq_pt/s2s/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/seass/code/SEASS/seq2seq_pt/s2s/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  File "/seass/code/SEASS/seq2seq_pt/s2s/xinit.py", line 218, in xavier_normal
    xavier_normal(tensor.data, gain=gain)
  [Previous line repeated 990 more times]
  File "/seass/code/SEASS/seq2seq_pt/s2s/xinit.py", line 217, in xavier_normal
    if isinstance(tensor, Variable):
RecursionError: maximum recursion depth exceeded
```

**Comment by magic282** [comment]
@kj-lai What is your PyTorch version?

**Comment by kj-lai** [comment]
It worked when i downgraded my pytorch from 0.4.0 to 0.3.1. Thank you and sorry for the trouble.
